baseURL = "https://deer-test1.netlify.app/"
disableLanguages = ["fr", "it", "de"]
disqusShortname = ""
googleAnalytics = ""
paginate = "6"
summaryLength = "30"
theme = "airspace-hugo"
timeZone = "UTC"
title = "The Deer of SIU"
[languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Alle Rechte vorbehalten."
languageCode = "de-DE"
languageName = "Deutsch"
weight = 3
[[languages.de.menu.main]]
hasChildren = true
name = "Mehr"
weight = 5
[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). All Rights Reserved."
languageCode = "en-US"
languageName = "English"
weight = 1
[[languages.en.menu.main]]
hasChildren = ""
name = ""
weight = ""
[languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tous droits réservés."
languageCode = "fr-FR"
languageName = "Français"
weight = 2
[[languages.fr.menu.main]]
hasChildren = true
name = "Plus"
weight = "8"
[languages.it]
contentDir = "content/italian"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti i diritti riservati."
languageCode = "it-IT"
languageName = "Italiano"
weight = "2"
[[languages.it.menu.main]]
hasChildren = false
name = "Più"
weight = "5"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = "2"
ordered = false
startLevel = "1"
[[menu.footer]]
name = "Servizio"
weight = 9
[[menu.footer]]
name = "Progetto"
weight = 6
[[menu.footer]]
name = "Tariffazione"
weight = 11
[[menu.footer]]
name = "Domande frequenti"
weight = 14
[[menu.footer]]
name = "Contatta"
weight = 17
[[menu.footer]]
name = "Chi siamo"
weight = 3
[[menu.footer]]
name = "Dienstleistung"
weight = 8
[[menu.footer]]
name = "Projekt"
weight = 5
[[menu.footer]]
name = "Preise"
weight = 10
[[menu.footer]]
name = "Häufige Fragen"
weight = 13
[[menu.footer]]
name = "Kontakt"
weight = 16
[[menu.footer]]
name = "Über uns"
weight = 2
[[menu.footer]]
name = "Servizio"
weight = 20
[[menu.footer]]
name = "Progetto"
weight = 15
[[menu.footer]]
name = "Tariffazione"
weight = 24
[[menu.footer]]
name = "Domande frequenti"
weight = 26
[[menu.footer]]
name = "Contatta"
weight = 28
[[menu.footer]]
name = "Chi siamo"
weight = 7
[[menu.footer]]
name = "Dienstleistung"
weight = 18
[[menu.footer]]
name = "Projekt"
weight = 12
[[menu.footer]]
name = "Preise"
weight = 23
[[menu.footer]]
name = "Häufige Fragen"
weight = 25
[[menu.footer]]
name = "Kontakt"
weight = 27
[[menu.footer]]
name = "Über uns"
weight = 4
[[menu.main]]
identifier = "blog"
name = "Blog"
weight = 16
[[menu.main]]
name = "Servizio"
parent = "Più"
weight = 4
[[menu.main]]
name = "Progetto"
weight = 14
[[menu.main]]
name = "Tariffazione"
parent = "Più"
weight = 9
[[menu.main]]
name = "Domande frequenti"
parent = "Più"
weight = 13
[[menu.main]]
name = "Contatta"
weight = 19
[[menu.main]]
name = "Chi siamo"
weight = 8
[[menu.main]]
name = "Pagina iniziale"
weight = 3
[[menu.main]]
name = "Dienstleistung"
parent = "Mehr"
weight = 2
[[menu.main]]
name = "Projekt"
weight = 12
[[menu.main]]
name = "Preise"
parent = "Mehr"
weight = 7
[[menu.main]]
name = "Häufige Fragen"
parent = "Mehr"
weight = 11
[[menu.main]]
name = "Kontakt"
weight = 18
[[menu.main]]
name = "Über uns"
weight = 6
[[menu.main]]
identifier = "blog"
name = "Blog"
weight = 28
[[menu.main]]
name = "Servizio"
parent = "Più"
weight = 15
[[menu.main]]
name = "Progetto"
weight = 27
[[menu.main]]
name = "Tariffazione"
parent = "Più"
weight = 23
[[menu.main]]
name = "Domande frequenti"
parent = "Più"
weight = 26
[[menu.main]]
name = "Contatta"
weight = 31
[[menu.main]]
name = "Chi siamo"
weight = 22
[[menu.main]]
name = "Pagina iniziale"
weight = 10
[[menu.main]]
name = "Dienstleistung"
parent = "Mehr"
weight = 5
[[menu.main]]
name = "Projekt"
weight = 25
[[menu.main]]
name = "Preise"
parent = "Mehr"
weight = 21
[[menu.main]]
name = "Häufige Fragen"
parent = "Mehr"
weight = 24
[[menu.main]]
name = "Kontakt"
weight = 30
[[menu.main]]
name = "Über uns"
weight = 17
[[menu.main]]
name = "Startseite"
weight = 1
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputs]
home = ["HTML"]
[params]
author = "SWEL"
description = "This is meta description"
image = "images/logo-1.png"
logo = "images/logo-1.png"
logo_width = "250px"
[params.contact]
address_descriptors = false
email = "deer@siu.edu"
location = "**Spatial Wildlife Ecology Lab**  Southern Illinois University, Carbondale, IL, 62901"
phone = "6184536946"
[params.contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
[params.cookies]
enable = true
expire_days = 2
[params.counter]
enable = true
username = ""
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "37.71515"
map_longitude = "-89.22260"
map_marker = "images/marker.png"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
