---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: this is meta description
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- name: see_rosalind_s_movements_here_
  type: include
  config: {}
  template: new-page
  label: See Rosalind's movements here!
  description: <a href="ID_88252.html" title="Rosalind" target="_blank">ID_88252.html</a>
- name: see_jacques__movements_here_
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: See Rosalind's movements here!
  description: <a href="ID_88252.html" title="Rosalind" target="_blank">ID_88252.html</a>
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
